---
- include: dependens.yml

- name: install php pakage rpm
  yum : name={{ item }} state=present
  with_items:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

- name: ensure php installed
  yum : name={{ item }} state=present
  with_items:
    - php56w
    - php56w-cli
    - php56w-fpm
    - php56w-mysql
    - php56w-devel
    - php56w-gd
    - php56w-pecl-memcache
    - php56w-pspell
    - php56w-snmp
    - php56w-xmlrpc
    - php56w-xml
    - php56w-bcmath
    - php56w-mbstring

- name: restart php56w-fpm
  service: name=php-fpm state=restarted  enabled=yes
